# target: real path
# source: path to create symlink


# Sample File
[[symlinks]]
target = "temp/file.txt"
source = "temp/hello/rename.txt"
filter = { env = ["test"] }


# Helix
[[symlinks]]
target = "helix"
source = "$XDG_CONFIG_HOME/helix"

[[symlinks]]
target = "helix"
source = "temp/helix"
filter = { env = ["test"] }


# WezTerm
[[symlinks]]
target = "git@github.com:iceflottante/oh-my-wezterm.git"
source = "temp/wezterm"
filter = { env = ["test"] }

[[symlinks]]
target = "temp/wezterm"
source = "$XDG_CONFIG_HOME/wezterm"
filter = { env = ["test"] }


# tmux
[[symlinks]]
target = "tmux"
source = "$HOME/.tmux"


# Rime
[[symlinks]]
target = "https://github.com/rimeinn/rime-moran.git -b simp"
source = "Rime"

[[symlinks]]
target = "Rime"
source = "$XDG_CONFIG_HOME/Rime"
filter = { os = ["windows", "linux"] }

[[symlinks]]
target = "Rime"
source = "$HOME/Library/Rime"
filter = { os = ["mac"] }

